export const DataBaseTexturePack = [
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "3opurTo.webp",
    variability_name: ["3opurTo"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "AMFIBIYA.webp",
    variability_name: ["AMFIBIYA", "АМФИБИЯ"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "BaXy.webp",
    variability_name: ["BaXy", "Бакси"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Maid_BaXy.webp",
    variability_name: ["Maid BaXy", "Горничная Бакси"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Bivrat.webp",
    variability_name: ["Bivrat", "Биврат"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Blackirita.webp",
    variability_name: ["Blackirita", "Блэки"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Blackiritacup.webp",
    variability_name: ["Blackiritacup", "Блэки Купальник"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Blackiritang.webp",
    variability_name: ["Blackiritang", "Блэкинг"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Blackirite.webp",
    variability_name: ["Blackirite", "Срань господня"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "BlackPirat.webp",
    variability_name: ["BlackPirat", "Пиратик", "Пират", "Чёрный Пират"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "ChancellorIkseew.webp",
    variability_name: ["ChancellorIkseew", "Канцлер"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "ClintFlames.webp",
    variability_name: ["ClintFlames", "Clint", "Клинт"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Cytrynid.webp",
    variability_name: [
      "Cytrynid",
      "Lemonid",
      "Desert Cytrynid",
      "Цитринид",
      "Лемонид",
      "Пустынный Лемонид",
      "Пустынный Цитринид",
    ],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Daesael.webp",
    variability_name: ["Daesael"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Dalandis.webp",
    variability_name: ["Dalandis", "Даландис"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "dooDUDKA.webp",
    variability_name: ["dooDUDKA", "Dudka", "Dudochka", "Дудка", "Дудочка"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "dunno59.webp",
    variability_name: ["dunno59", "дуно"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "dunno59c.webp",
    variability_name: ["dunno59c", "Дунно Короткобибый"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "dunno69.webp",
    variability_name: ["dunno69"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "EagleRu.webp",
    variability_name: ["EagleRu", "Вождя", "Игл"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "EUGENlJUS.webp",
    variability_name: ["EUGENlJUS", "Евгениюс"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Felgur_Tatum.webp",
    variability_name: ["Felgur", "Felgur_Tatum", "Фелгур", "Фелгур Татум"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "G1eb04k0.webp",
    variability_name: ["G1eb04k0", "Glebo4ko", "Gleb", "Глебочко", "Глеб"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "gerhugwsif.webp",
    variability_name: ["ger", "ger", "gerhugwsif", "Гер"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Hazquard.webp",
    variability_name: ["Hazquard", "Хаз"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "HuDreY.webp",
    variability_name: ["HuDreY"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "IronCAT_.webp",
    variability_name: ["IronCAT_", "IronCAT", "Железный Кот"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "ItzClandex.webp",
    variability_name: ["ItzClandex", "Clandex", "Кландекс"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Jean_Viento.webp",
    variability_name: ["Jean", "Jean_Viento", "Жаник"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Pr0sTiK.webp",
    variability_name: ["Prostik", "Pr0sTiK", "Jean Old", "Простик", "Жан Олд"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "_JohngeaR_.webp",
    variability_name: ["_JohngeaR_", "JohngeaR", "John", "Джонгир", "Джон"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "K0hNk_Yt.webp",
    variability_name: ["K0hNk_Yt", "KohNk_Yt", "K0hNk", "KohNk"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Kermitik.webp",
    variability_name: ["Kermitik", "Kermit", "Кермитик", "Кермит"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Kerubifi.webp",
    variability_name: ["Kerubifi", "Керубифи"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Killermax2012.webp",
    variability_name: [
      "Killermax2012",
      "Killermax",
      "Киллермакс2012",
      "Киллермакс",
    ],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "3opurTo.webp",
    variability_name: ["KIPO4", "Кипа"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "KIPO4.webp",
    variability_name: ["Krendilek37", "Krendilek", "Крендилёк"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Krogut.webp",
    variability_name: ["Krogut", "Крогут"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "kurlykepty.webp",
    variability_name: ["kurlykepty", "Kurlyk", "Курлык"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Li_Ora.webp",
    variability_name: ["Li_Ora", "Лиора"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Lucky_Sword.webp",
    variability_name: ["Lucky_Sword", "Лаки"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Lucky_Sword_Imperia.webp",
    variability_name: [
      "Lucky_Sword Imperia",
      "Lucky_Swordi",
      "Лакии",
      "Лаки Империя",
    ],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Lus7.webp",
    variability_name: ["Lus7", "Lu", "Luseven", "Лу", "Лу Семь"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Mad_Chiffa.webp",
    variability_name: ["Mad_Chiffa", "Chiffa", "Безумный Чиффа", "Чиффа"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Matychka.webp",
    variability_name: ["Matychka", "Матюша", "Матюшка"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "McQyaid.webp",
    variability_name: ["McQyaid"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "_Mekhanit_.webp",
    variability_name: ["_Mekhanit_", "Mekhanit", "Механит"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Melimops.webp",
    variability_name: ["Melimops"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "mirage3000.webp",
    variability_name: ["mirage3000", "mirage", "Мираж", "Мираж3000"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "MissAnnet.webp",
    variability_name: ["MissAnnet", "Annet", "МиссАннет", "Аннет"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Mr_Green25.webp",
    variability_name: ["Mr_Green25"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Niksa_Viento.webp",
    variability_name: ["Niksa", "Niksa_Viento", "Никса", "Никс"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Niksette.webp",
    variability_name: ["Niksette", "Niksa Old", "Никсетте", "Никса Олд"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "OMNIONI.webp",
    variability_name: ["OMNIONI"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Oxana__.webp",
    variability_name: ["Oxana__", "Oxana", "Оксана"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "PD_LEDER.webp",
    variability_name: ["PD_LEDER"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "prestig9110.webp",
    variability_name: ["prestig9110", "Престиж"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Pure_VesseI.webp",
    variability_name: ["Pure_VesseI"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "roy_frost.webp",
    variability_name: ["roy_frost", "royfrost", "Рой Фрост", "РойФрост"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "SabLi.webp",
    variability_name: ["SabLi", "Сабля"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Sefaa.webp",
    variability_name: ["Sefaa", "Сефа", "Лёва"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "SenSid.webp",
    variability_name: ["SenSid"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "SoftPanda3.webp",
    variability_name: ["SoftPanda3", "Panda", "SoftPanda", "Пандочка", "Панда"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "SoftPanda3c.webp",
    variability_name: [
      "SoftPanda3c",
      "SoftPandac",
      "Pandac",
      "Пандас",
      "Пандочкас",
    ],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "SoftPanda3ng.webp",
    variability_name: [
      "SoftPanda3ng",
      "SoftPandang",
      "Pandang",
      "Панданг",
      "Пандочканг",
    ],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "SolyankaXD.webp",
    variability_name: [
      "SolyankaXD",
      "Solyanka",
      "Soniaka",
      "Soni4ka",
      "Солянка",
      "Соничка",
    ],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Steinyasha.webp",
    variability_name: ["Steinyasha", "Stein", "Штейн"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "UTKNSS.webp",
    variability_name: ["UTKNSS", "UTKNS", "Утконос"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "VessAy.webp",
    variability_name: ["VessAy"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "VessAyR.webp",
    variability_name: ["VessAyR", "Грэг"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Vio.webp",
    variability_name: ["Vio", "Вио"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Vonderan.webp",
    variability_name: ["Vonderan", "Vonder", "Вондеран", "Вондер"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "wanier680.webp",
    variability_name: ["wanier680", "wanier"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "Wapwolf.webp",
    variability_name: ["Wapwolf", "ВапВульф"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "WiCry.webp",
    variability_name: ["WiCry", "Вай"],
  },
  {
    main_item: "totem_of_undying",
    main_item_ru: "Тотем",
    img_custom: "ytka_sorry_t9.webp",
    variability_name: ["Ytka", "ytka_sorry_t9", "Утка", "Уточка"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "crimson.webp",
    variability_name: ["crimson"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "davinci.webp",
    variability_name: ["davinci"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "demon.webp",
    variability_name: ["demon"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "dragonfly.webp",
    variability_name: ["dragonfly"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "dreamtime.webp",
    variability_name: ["dreamtime"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "elysium.webp",
    variability_name: ["elysium"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "fairy.webp",
    variability_name: ["fairy"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "golden_beetle.webp",
    variability_name: ["golden_beetle"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "green_beetle.webp",
    variability_name: ["green_beetle"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "green_dragon.webp",
    variability_name: ["green_dragon"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "Nova.webp",
    variability_name: ["nova"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "phoenix.webp",
    variability_name: ["phoenix"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "priest.webp",
    variability_name: ["priest"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "prime.webp",
    variability_name: ["prime"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "red_dragon.webp",
    variability_name: ["red_dragon"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "solar.webp",
    variability_name: ["solar"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "sunset.webp",
    variability_name: ["sunset"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "underworld.webp",
    variability_name: ["underworld"],
  },
  {
    main_item: "ELYTRA",
    main_item_ru: "Елитры",
    img_custom: "warped.webp",
    variability_name: ["warped"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "archer_hat.webp",
    variability_name: ["Шляпа лучника"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "armorer_hat.webp",
    variability_name: ["Шляпа бронника"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "arrow.webp",
    variability_name: ["Стрела"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "crown.webp",
    variability_name: ["Корона"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "elf.webp",
    variability_name: ["Эльф"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "farmer_hat.webp",
    variability_name: ["Шляпа фермера"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "ficher_hat.webp",
    variability_name: ["Шляпа рыбака"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "lib_hat.webp",
    variability_name: ["Шляпа библиотекаря"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "pen.webp",
    variability_name: ["Карандаш"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "santa.webp",
    variability_name: ["Санта"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "trident.webp",
    variability_name: ["Трезубец"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "witch.webp",
    variability_name: ["Шляпа ведьмы"],
  },
  {
    main_item: "CARVED_PUMPKIN",
    main_item_ru: "вырезаную тыкву",
    img_custom: "wreath.webp",
    variability_name: ["Венок"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "beer.webp",
    variability_name: ["Пиво", "Beer"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "boba.webp",
    variability_name: ["Пузырьковый чай", "Boba"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "champagne.webp",
    variability_name: ["Шампанское", "Champagne"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "coffee.webp",
    variability_name: ["Кофе", "Coffee"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "hot_chocolate.webp",
    variability_name: ["Горячий шоколад", "Hot chocolate"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "juise.webp",
    variability_name: ["Сок", "Juice"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "margarita.webp",
    variability_name: ["Маргарита", "Margarita"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "martini.webp",
    variability_name: ["Мартини", "Martini"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "pinacolada.webp",
    variability_name: ["Пинаколада", "Pinacolada"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "shot.webp",
    variability_name: ["Шот", "Shot"],
  },
  {
    main_item: "POTION",
    main_item_ru: "любое зелье",
    img_custom: "wine.webp",
    variability_name: ["Вино", "Wine"],
  },
  {
    main_item: "SWEET_BERRIES",
    main_item_ru: "сладкие ягоды",
    img_custom: "blueberry.webp",
    variability_name: ["Черника", "Blueberry"],
  },
  {
    main_item: "SWEET_BERRIES",
    main_item_ru: "сладкие ягоды",
    img_custom: "cherries.webp",
    variability_name: ["Вишня", "Cherries"],
  },
  {
    main_item: "SWEET_BERRIES",
    main_item_ru: "сладкие ягоды",
    img_custom: "grapes_concord.webp",
    variability_name: ["Синий виноград", "Blue grapes"],
  },
  {
    main_item: "SWEET_BERRIES",
    main_item_ru: "сладкие ягоды",
    img_custom: "grapes_green.webp",
    variability_name: ["Зелёный виноград", "Green grapes"],
  },
  {
    main_item: "SWEET_BERRIES",
    main_item_ru: "сладкие ягоды",
    img_custom: "Raspberry.webp",
    variability_name: ["Малина", "Raspberry"],
  },
  {
    main_item: "SWEET_BERRIES",
    main_item_ru: "сладкие ягоды",
    img_custom: "strawberry.webp",
    variability_name: ["Клубника", "Strawberry"],
  },
  {
    main_item: "BREAD",
    main_item_ru: "хлеб",
    img_custom: "donut_chocolate_glaze.webp",
    variability_name: ["Шоколадный пончик", "Chocolate donut"],
  },
  {
    main_item: "BREAD",
    main_item_ru: "хлеб",
    img_custom: "donut_sprinkles.webp",
    variability_name: ["Глазурный пончик", "Sprinkle donut"],
  },
  {
    main_item: "BREAD",
    main_item_ru: "хлеб",
    img_custom: "pancakes.webp",
    variability_name: ["Блины", "Pancakes"],
  },
  {
    main_item: "COOKIE",
    main_item_ru: "печенье",
    img_custom: "candycane_peppermint.webp",
    variability_name: ["Леденец", "Candy cane"],
  },
  {
    main_item: "COOKIE",
    main_item_ru: "печенье",
    img_custom: "caramelapple.webp",
    variability_name: ["Карамельное яблоко", "Caramel apple"],
  },
  {
    main_item: "COOKIE",
    main_item_ru: "печенье",
    img_custom: "Cottoncandy.webp",
    variability_name: ["Сладкая вата", "Cottoncandy"],
  },
  {
    main_item: "COOKIE",
    main_item_ru: "печенье",
    img_custom: "ginger_creeper.webp",
    variability_name: ["Пряник", "Gingerbread"],
  },
  {
    main_item: "COOKIE",
    main_item_ru: "печенье",
    img_custom: "icecream_chocolate.webp",
    variability_name: ["Шоколадное мороженое", "Chocolate icecream"],
  },
  {
    main_item: "COOKIE",
    main_item_ru: "печенье",
    img_custom: "icecream_vanilla.webp",
    variability_name: ["Ванильное мороженое", "Vanilla icecream"],
  },
  {
    main_item: "COOKIE",
    main_item_ru: "печенье",
    img_custom: "Oreo.webp",
    variability_name: ["Орео", "Oreo"],
  },
  {
    main_item: "COOKIE",
    main_item_ru: "печенье",
    img_custom: "pretzel.webp",
    variability_name: ["Крендель", "Pretzel"],
  },
  {
    main_item: "COOKED_SALMON",
    main_item_ru: "жаренный лосось",
    img_custom: "nigiri.webp",
    variability_name: ["Нигири", "Nigiri"],
  },
  {
    main_item: "SALMON",
    main_item_ru: "сырой лосось",
    img_custom: "onigiri.webp",
    variability_name: ["Нигири", "Nigiri"],
  },
  {
    main_item: "DRIED_KELP",
    main_item_ru: "сушённую ламинарию",
    img_custom: "onigiri.webp",
    variability_name: ["Онигири", "Onigiri"],
  },
  {
    main_item: "COOKED_COD",
    main_item_ru: "жаренную треску",
    img_custom: "sushi.webp",
    variability_name: ["Суши", "Sushi"],
  },
  {
    main_item: "COD",
    main_item_ru: "сырую треску",
    img_custom: "sushi.webp",
    variability_name: ["Суши", "Sushi"],
  },
  {
    main_item: "APPLE",
    main_item_ru: "яблоко",
    img_custom: "apricot.webp",
    variability_name: ["Абрикос", "Apricot"],
  },
  {
    main_item: "APPLE",
    main_item_ru: "яблоко",
    img_custom: "banana.webp",
    variability_name: ["Банан", "Banana"],
  },
  {
    main_item: "APPLE",
    main_item_ru: "яблоко",
    img_custom: "coconut.webp",
    variability_name: ["Кокос", "Coconut"],
  },
  {
    main_item: "APPLE",
    main_item_ru: "яблоко",
    img_custom: "mango.webp",
    variability_name: ["Манго", "Mango"],
  },
  {
    main_item: "APPLE",
    main_item_ru: "яблоко",
    img_custom: "peach.webp",
    variability_name: ["Персик", "Peach"],
  },
  {
    main_item: "APPLE",
    main_item_ru: "яблоко",
    img_custom: "pear.webp",
    variability_name: ["Груша", "Pear"],
  },
  {
    main_item: "APPLE",
    main_item_ru: "яблоко",
    img_custom: "pineapple.webp",
    variability_name: ["Ананас", "Pineapple"],
  },
  {
    main_item: "COOKED_BEEF",
    main_item_ru: "стейк",
    img_custom: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main_item: "COOKED_CHICKEN",
    main_item_ru: "жареную курятину",
    img_custom: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main_item: "COOKED_MUTTON",
    main_item_ru: "жареную баринину",
    img_custom: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main_item: "COOKED_PORKCHOP",
    main_item_ru: "жареную свинину",
    img_custom: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main_item: "COOKED_RABBIT",
    main_item_ru: "жареную крольчатину",
    img_custom: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main_item: "COOKED_BEEF",
    main_item_ru: "стейк",
    img_custom: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main_item: "COOKED_CHICKEN",
    main_item_ru: "жареную курятину",
    img_custom: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main_item: "COOKED_MUTTON",
    main_item_ru: "жареную баринину",
    img_custom: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main_item: "COOKED_PORKCHOP",
    main_item_ru: "жареную свинину",
    img_custom: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main_item: "COOKED_RABBIT",
    main_item_ru: "жареную крольчатину",
    img_custom: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main_item: "COOKED_BEEF",
    main_item_ru: "стейк",
    img_custom: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main_item: "COOKED_CHICKEN",
    main_item_ru: "жареную курятину",
    img_custom: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main_item: "COOKED_MUTTON",
    main_item_ru: "жареную баринину",
    img_custom: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main_item: "COOKED_PORKCHOP",
    main_item_ru: "жареную свинину",
    img_custom: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main_item: "COOKED_RABBIT",
    main_item_ru: "жареную крольчатину",
    img_custom: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main_item: "COOKED_BEEF",
    main_item_ru: "стейк",
    img_custom: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main_item: "COOKED_CHICKEN",
    main_item_ru: "жареную курятину",
    img_custom: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main_item: "COOKED_MUTTON",
    main_item_ru: "жареную баринину",
    img_custom: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main_item: "COOKED_PORKCHOP",
    main_item_ru: "жареную свинину",
    img_custom: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main_item: "COOKED_RABBIT",
    main_item_ru: "жареную крольчатину",
    img_custom: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main_item: "COOKED_BEEF",
    main_item_ru: "стейк",
    img_custom: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main_item: "COOKED_CHICKEN",
    main_item_ru: "жареную курятину",
    img_custom: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main_item: "COOKED_MUTTON",
    main_item_ru: "жареную баринину",
    img_custom: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main_item: "COOKED_PORKCHOP",
    main_item_ru: "жареную свинину",
    img_custom: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main_item: "COOKED_RABBIT",
    main_item_ru: "жареную крольчатину",
    img_custom: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main_item: "COOKED_BEEF",
    main_item_ru: "стейк",
    img_custom: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main_item: "COOKED_CHICKEN",
    main_item_ru: "жареную курятину",
    img_custom: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main_item: "COOKED_MUTTON",
    main_item_ru: "жареную баринину",
    img_custom: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main_item: "COOKED_PORKCHOP",
    main_item_ru: "жареную свинину",
    img_custom: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main_item: "COOKED_RABBIT",
    main_item_ru: "жареную крольчатину",
    img_custom: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main_item: "COOKED_CHICKEN",
    main_item_ru: "жареную курятину",
    img_custom: "chickenwings.webp",
    variability_name: ["Крылышки", "Chickenwings"],
  },
  {
    main_item: "PUMPKIN_PIE",
    main_item_ru: "тыквенный пирог",
    img_custom: "chocolate_pie.webp",
    variability_name: ["Шоколадный пирог", "Chocolate pie"],
  },
  {
    main_item: "PUMPKIN_PIE",
    main_item_ru: "тыквенный пирог",
    img_custom: "raspberry_pie.webp",
    variability_name: ["Малиновый пирог", "Raspberry pie"],
  },
  {
    main_item: "PUMPKIN_PIE",
    main_item_ru: "тыквенный пирог",
    img_custom: "trifle.webp",
    variability_name: ["Трайфл", "Trifle"],
  },
  {
    main_item: "MUSHROOM_STEW",
    main_item_ru: "тушённые грибы",
    img_custom: "broth.webp",
    variability_name: ["Бульон", "Broth"],
  },
  {
    main_item: "MUSHROOM_STEW",
    main_item_ru: "тушённые грибы",
    img_custom: "pelmenei.webp",
    variability_name: ["Пельмени", "Pelmenei"],
  },
];