export const DataBaseTexturePack = [
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "3opurTo.webp",
    variability_name: ["3opurTo"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "AMFIBIYA.webp",
    variability_name: ["AMFIBIYA", "АМФИБИЯ"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "BaXy.webp",
    variability_name: ["BaXy", "Бакси"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Maid_BaXy.webp",
    variability_name: ["Maid BaXy", "Горничная Бакси"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Bivrat.webp",
    variability_name: ["Bivrat", "Биврат"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Blackirita.webp",
    variability_name: ["Blackirita", "Блэки"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Blackiritacup.webp",
    variability_name: ["Blackiritacup", "Блэки Купальник"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Blackiritang.webp",
    variability_name: ["Blackiritang", "Блэкинг"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Blackirite.webp",
    variability_name: ["Blackirite", "Срань господня"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "BlackPirat.webp",
    variability_name: ["BlackPirat", "Пиратик", "Пират", "Чёрный Пират"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "ChancellorIkseew.webp",
    variability_name: ["ChancellorIkseew", "Канцлер"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "ClintFlames.webp",
    variability_name: ["ClintFlames", "Clint", "Клинт"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Cytrynid.webp",
    variability_name: [
      "Cytrynid",
      "Lemonid",
      "Desert Cytrynid",
      "Цитринид",
      "Лемонид",
      "Пустынный Лемонид",
      "Пустынный Цитринид",
    ],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Daesael.webp",
    variability_name: ["Daesael"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Dalandis.webp",
    variability_name: ["Dalandis", "Даландис"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "dooDUDKA.webp",
    variability_name: ["dooDUDKA", "Dudka", "Dudochka", "Дудка", "Дудочка"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "dunno59.webp",
    variability_name: ["dunno59", "дуно"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "dunno59c.webp",
    variability_name: ["dunno59c", "Дунно Короткобибый"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "dunno69.webp",
    variability_name: ["dunno69"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "EagleRu.webp",
    variability_name: ["EagleRu", "Вождя", "Игл"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "EUGENlJUS.webp",
    variability_name: ["EUGENlJUS", "Евгениюс"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Felgur_Tatum.webp",
    variability_name: ["Felgur", "Felgur_Tatum", "Фелгур", "Фелгур Татум"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "G1eb04k0.webp",
    variability_name: ["G1eb04k0", "Glebo4ko", "Gleb", "Глебочко", "Глеб"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "gerhugwsif.webp",
    variability_name: ["ger", "ger", "gerhugwsif", "Гер"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Hazquard.webp",
    variability_name: ["Hazquard", "Хаз"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "HuDreY.webp",
    variability_name: ["HuDreY"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "IronCAT_.webp",
    variability_name: ["IronCAT_", "IronCAT", "Железный Кот"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "ItzClandex.webp",
    variability_name: ["ItzClandex", "Clandex", "Кландекс"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Jean_Viento.webp",
    variability_name: ["Jean", "Jean_Viento", "Жаник"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Pr0sTiK.webp",
    variability_name: ["Prostik", "Pr0sTiK", "Jean Old", "Простик", "Жан Олд"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "_JohngeaR_.webp",
    variability_name: ["_JohngeaR_", "JohngeaR", "John", "Джонгир", "Джон"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "K0hNk_Yt.webp",
    variability_name: ["K0hNk_Yt", "KohNk_Yt", "K0hNk", "KohNk"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Kermitik.webp",
    variability_name: ["Kermitik", "Kermit", "Кермитик", "Кермит"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Kerubifi.webp",
    variability_name: ["Kerubifi", "Керубифи"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Killermax2012.webp",
    variability_name: [
      "Killermax2012",
      "Killermax",
      "Киллермакс2012",
      "Киллермакс",
    ],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "3opurTo.webp",
    variability_name: ["KIPO4", "Кипа"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "KIPO4.webp",
    variability_name: ["Krendilek37", "Krendilek", "Крендилёк"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Krogut.webp",
    variability_name: ["Krogut", "Крогут"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "kurlykepty.webp",
    variability_name: ["kurlykepty", "Kurlyk", "Курлык"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Li_Ora.webp",
    variability_name: ["Li_Ora", "Лиора"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Lucky_Sword.webp",
    variability_name: ["Lucky_Sword", "Лаки"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Lucky_Sword_Imperia.webp",
    variability_name: [
      "Lucky_Sword Imperia",
      "Lucky_Swordi",
      "Лакии",
      "Лаки Империя",
    ],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Lus7.webp",
    variability_name: ["Lus7", "Lu", "Luseven", "Лу", "Лу Семь"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Mad_Chiffa.webp",
    variability_name: ["Mad_Chiffa", "Chiffa", "Безумный Чиффа", "Чиффа"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Matychka.webp",
    variability_name: ["Matychka", "Матюша", "Матюшка"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "McQyaid.webp",
    variability_name: ["McQyaid"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "_Mekhanit_.webp",
    variability_name: ["_Mekhanit_", "Mekhanit", "Механит"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Melimops.webp",
    variability_name: ["Melimops"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "mirage3000.webp",
    variability_name: ["mirage3000", "mirage", "Мираж", "Мираж3000"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "MissAnnet.webp",
    variability_name: ["MissAnnet", "Annet", "МиссАннет", "Аннет"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Mr_Green25.webp",
    variability_name: ["Mr_Green25"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Niksa_Viento.webp",
    variability_name: ["Niksa", "Niksa_Viento", "Никса", "Никс"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Niksette.webp",
    variability_name: ["Niksette", "Niksa Old", "Никсетте", "Никса Олд"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "OMNIONI.webp",
    variability_name: ["OMNIONI"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Oxana__.webp",
    variability_name: ["Oxana__", "Oxana", "Оксана"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "PD_LEDER.webp",
    variability_name: ["PD_LEDER"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "prestig9110.webp",
    variability_name: ["prestig9110", "Престиж"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Pure_VesseI.webp",
    variability_name: ["Pure_VesseI"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "roy_frost.webp",
    variability_name: ["roy_frost", "royfrost", "Рой Фрост", "РойФрост"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "SabLi.webp",
    variability_name: ["SabLi", "Сабля"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Sefaa.webp",
    variability_name: ["Sefaa", "Сефа", "Лёва"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "SenSid.webp",
    variability_name: ["SenSid"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "SoftPanda3.webp",
    variability_name: ["SoftPanda3", "Panda", "SoftPanda", "Пандочка", "Панда"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "SoftPanda3c.webp",
    variability_name: [
      "SoftPanda3c",
      "SoftPandac",
      "Pandac",
      "Пандас",
      "Пандочкас",
    ],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "SoftPanda3ng.webp",
    variability_name: [
      "SoftPanda3ng",
      "SoftPandang",
      "Pandang",
      "Панданг",
      "Пандочканг",
    ],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "SolyankaXD.webp",
    variability_name: [
      "SolyankaXD",
      "Solyanka",
      "Soniaka",
      "Soni4ka",
      "Солянка",
      "Соничка",
    ],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Steinyasha.webp",
    variability_name: ["Steinyasha", "Stein", "Штейн"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "UTKNSS.webp",
    variability_name: ["UTKNSS", "UTKNS", "Утконос"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "VessAy.webp",
    variability_name: ["VessAy"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "VessAyR.webp",
    variability_name: ["VessAyR", "Грэг"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Vio.webp",
    variability_name: ["Vio", "Вио"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Vonderan.webp",
    variability_name: ["Vonderan", "Vonder", "Вондеран", "Вондер"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "wanier680.webp",
    variability_name: ["wanier680", "wanier"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "Wapwolf.webp",
    variability_name: ["Wapwolf", "ВапВульф"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "WiCry.webp",
    variability_name: ["WiCry", "Вай"],
  },
  {
    main: "TOTEM_OF_UNDYING",
    info_item: "Тотем",
    img: "ytka_sorry_t9.webp",
    variability_name: ["Ytka", "ytka_sorry_t9", "Утка", "Уточка"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "crimson.webp",
    variability_name: ["crimson"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "davinci.webp",
    variability_name: ["davinci"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "demon.webp",
    variability_name: ["demon"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "dragonfly.webp",
    variability_name: ["dragonfly"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "dreamtime.webp",
    variability_name: ["dreamtime"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "elysium.webp",
    variability_name: ["elysium"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "fairy.webp",
    variability_name: ["fairy"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "golden_beetle.webp",
    variability_name: ["golden_beetle"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "green_beetle.webp",
    variability_name: ["green_beetle"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "green_dragon.webp",
    variability_name: ["green_dragon"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "Nova.webp",
    variability_name: ["nova"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "phoenix.webp",
    variability_name: ["phoenix"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "priest.webp",
    variability_name: ["priest"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "prime.webp",
    variability_name: ["prime"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "red_dragon.webp",
    variability_name: ["red_dragon"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "solar.webp",
    variability_name: ["solar"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "sunset.webp",
    variability_name: ["sunset"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "underworld.webp",
    variability_name: ["underworld"],
  },
  {
    main: "ELYTRA",
    info_item: "Елитры",
    img: "warped.webp",
    variability_name: ["warped"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "archer_hat.webp",
    variability_name: ["Шляпа лучника"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "armorer_hat.webp",
    variability_name: ["Шляпа бронника"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "arrow.webp",
    variability_name: ["Стрела"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "crown.webp",
    variability_name: ["Корона"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "elf.webp",
    variability_name: ["Эльф"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "farmer_hat.webp",
    variability_name: ["Шляпа фермера"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "ficher_hat.webp",
    variability_name: ["Шляпа рыбака"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "lib_hat.webp",
    variability_name: ["Шляпа библиотекаря"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "pen.webp",
    variability_name: ["Карандаш"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "santa.webp",
    variability_name: ["Санта"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "trident.webp",
    variability_name: ["Трезубец"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "witch.webp",
    variability_name: ["Шляпа ведьмы"],
  },
  {
    main: "CARVED_PUMPKIN",
    info_item: "вырезаную тыкву",
    img: "wreath.webp",
    variability_name: ["Венок"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "beer.webp",
    variability_name: ["Пиво", "Beer"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "boba.webp",
    variability_name: ["Пузырьковый чай", "Boba"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "champagne.webp",
    variability_name: ["Шампанское", "Champagne"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "coffee.webp",
    variability_name: ["Кофе", "Coffee"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "hot_chocolate.webp",
    variability_name: ["Горячий шоколад", "Hot chocolate"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "juise.webp",
    variability_name: ["Сок", "Juice"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "margarita.webp",
    variability_name: ["Маргарита", "Margarita"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "martini.webp",
    variability_name: ["Мартини", "Martini"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "pinacolada.webp",
    variability_name: ["Пинаколада", "Pinacolada"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "shot.webp",
    variability_name: ["Шот", "Shot"],
  },
  {
    main: "POTION",
    info_item: "любое зелье",
    img: "wine.webp",
    variability_name: ["Вино", "Wine"],
  },
  {
    main: "SWEET_BERRIES",
    info_item: "сладкие ягоды",
    img: "blueberry.webp",
    variability_name: ["Черника", "Blueberry"],
  },
  {
    main: "SWEET_BERRIES",
    info_item: "сладкие ягоды",
    img: "cherries.webp",
    variability_name: ["Вишня", "Cherries"],
  },
  {
    main: "SWEET_BERRIES",
    info_item: "сладкие ягоды",
    img: "grapes_concord.webp",
    variability_name: ["Синий виноград", "Blue grapes"],
  },
  {
    main: "SWEET_BERRIES",
    info_item: "сладкие ягоды",
    img: "grapes_green.webp",
    variability_name: ["Зелёный виноград", "Green grapes"],
  },
  {
    main: "SWEET_BERRIES",
    info_item: "сладкие ягоды",
    img: "Raspberry.webp",
    variability_name: ["Малина", "Raspberry"],
  },
  {
    main: "SWEET_BERRIES",
    info_item: "сладкие ягоды",
    img: "strawberry.webp",
    variability_name: ["Клубника", "Strawberry"],
  },
  {
    main: "BREAD",
    info_item: "хлеб",
    img: "donut_chocolate_glaze.webp",
    variability_name: ["Шоколадный пончик", "Chocolate donut"],
  },
  {
    main: "BREAD",
    info_item: "хлеб",
    img: "donut_sprinkles.webp",
    variability_name: ["Глазурный пончик", "Sprinkle donut"],
  },
  {
    main: "BREAD",
    info_item: "хлеб",
    img: "pancakes.webp",
    variability_name: ["Блины", "Pancakes"],
  },
  {
    main: "COOKIE",
    info_item: "печенье",
    img: "candycane_peppermint.webp",
    variability_name: ["Леденец", "Candy cane"],
  },
  {
    main: "COOKIE",
    info_item: "печенье",
    img: "caramelapple.webp",
    variability_name: ["Карамельное яблоко", "Caramel apple"],
  },
  {
    main: "COOKIE",
    info_item: "печенье",
    img: "Cottoncandy.webp",
    variability_name: ["Сладкая вата", "Cottoncandy"],
  },
  {
    main: "COOKIE",
    info_item: "печенье",
    img: "ginger_creeper.webp",
    variability_name: ["Пряник", "Gingerbread"],
  },
  {
    main: "COOKIE",
    info_item: "печенье",
    img: "icecream_chocolate.webp",
    variability_name: ["Шоколадное мороженое", "Chocolate icecream"],
  },
  {
    main: "COOKIE",
    info_item: "печенье",
    img: "icecream_vanilla.webp",
    variability_name: ["Ванильное мороженое", "Vanilla icecream"],
  },
  {
    main: "COOKIE",
    info_item: "печенье",
    img: "Oreo.webp",
    variability_name: ["Орео", "Oreo"],
  },
  {
    main: "COOKIE",
    info_item: "печенье",
    img: "pretzel.webp",
    variability_name: ["Крендель", "Pretzel"],
  },
  {
    main: "COOKED_SALMON",
    info_item: "жаренный лосось",
    img: "nigiri.webp",
    variability_name: ["Нигири", "Nigiri"],
  },
  {
    main: "SALMON",
    info_item: "сырой лосось",
    img: "onigiri.webp",
    variability_name: ["Нигири", "Nigiri"],
  },
  {
    main: "DRIED_KELP",
    info_item: "сушённую ламинарию",
    img: "onigiri.webp",
    variability_name: ["Онигири", "Onigiri"],
  },
  {
    main: "COOKED_COD",
    info_item: "жаренную треску",
    img: "sushi.webp",
    variability_name: ["Суши", "Sushi"],
  },
  {
    main: "COD",
    info_item: "сырую треску",
    img: "sushi.webp",
    variability_name: ["Суши", "Sushi"],
  },
  {
    main: "APPLE",
    info_item: "яблоко",
    img: "apricot.webp",
    variability_name: ["Абрикос", "Apricot"],
  },
  {
    main: "APPLE",
    info_item: "яблоко",
    img: "banana.webp",
    variability_name: ["Банан", "Banana"],
  },
  {
    main: "APPLE",
    info_item: "яблоко",
    img: "coconut.webp",
    variability_name: ["Кокос", "Coconut"],
  },
  {
    main: "APPLE",
    info_item: "яблоко",
    img: "mango.webp",
    variability_name: ["Манго", "Mango"],
  },
  {
    main: "APPLE",
    info_item: "яблоко",
    img: "peach.webp",
    variability_name: ["Персик", "Peach"],
  },
  {
    main: "APPLE",
    info_item: "яблоко",
    img: "pear.webp",
    variability_name: ["Груша", "Pear"],
  },
  {
    main: "APPLE",
    info_item: "яблоко",
    img: "pineapple.webp",
    variability_name: ["Ананас", "Pineapple"],
  },
  {
    main: "COOKED_BEEF",
    info_item: "стейк",
    img: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main: "COOKED_CHICKEN",
    info_item: "жареную курятину",
    img: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main: "COOKED_MUTTON",
    info_item: "жареную баринину",
    img: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main: "COOKED_PORKCHOP",
    info_item: "жареную свинину",
    img: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main: "COOKED_RABBIT",
    info_item: "жареную крольчатину",
    img: "burger.webp",
    variability_name: ["Бургер", "Burger"],
  },
  {
    main: "COOKED_BEEF",
    info_item: "стейк",
    img: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main: "COOKED_CHICKEN",
    info_item: "жареную курятину",
    img: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main: "COOKED_MUTTON",
    info_item: "жареную баринину",
    img: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main: "COOKED_PORKCHOP",
    info_item: "жареную свинину",
    img: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main: "COOKED_RABBIT",
    info_item: "жареную крольчатину",
    img: "burrito.webp",
    variability_name: ["Бурито", "Burrito"],
  },
  {
    main: "COOKED_BEEF",
    info_item: "стейк",
    img: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main: "COOKED_CHICKEN",
    info_item: "жареную курятину",
    img: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main: "COOKED_MUTTON",
    info_item: "жареную баринину",
    img: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main: "COOKED_PORKCHOP",
    info_item: "жареную свинину",
    img: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main: "COOKED_RABBIT",
    info_item: "жареную крольчатину",
    img: "hotdog.webp",
    variability_name: ["Хотдог", "Hotdog"],
  },
  {
    main: "COOKED_BEEF",
    info_item: "стейк",
    img: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main: "COOKED_CHICKEN",
    info_item: "жареную курятину",
    img: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main: "COOKED_MUTTON",
    info_item: "жареную баринину",
    img: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main: "COOKED_PORKCHOP",
    info_item: "жареную свинину",
    img: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main: "COOKED_RABBIT",
    info_item: "жареную крольчатину",
    img: "pizza.webp",
    variability_name: ["Пицца", "Pizza"],
  },
  {
    main: "COOKED_BEEF",
    info_item: "стейк",
    img: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main: "COOKED_CHICKEN",
    info_item: "жареную курятину",
    img: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main: "COOKED_MUTTON",
    info_item: "жареную баринину",
    img: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main: "COOKED_PORKCHOP",
    info_item: "жареную свинину",
    img: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main: "COOKED_RABBIT",
    info_item: "жареную крольчатину",
    img: "sausage.webp",
    variability_name: ["Сосиска", "Sausage"],
  },
  {
    main: "COOKED_BEEF",
    info_item: "стейк",
    img: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main: "COOKED_CHICKEN",
    info_item: "жареную курятину",
    img: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main: "COOKED_MUTTON",
    info_item: "жареную баринину",
    img: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main: "COOKED_PORKCHOP",
    info_item: "жареную свинину",
    img: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main: "COOKED_RABBIT",
    info_item: "жареную крольчатину",
    img: "taco.webp",
    variability_name: ["Тако", "Taco"],
  },
  {
    main: "COOKED_CHICKEN",
    info_item: "жареную курятину",
    img: "chickenwings.webp",
    variability_name: ["Крылышки", "Chickenwings"],
  },
  {
    main: "PUMPKIN_PIE",
    info_item: "тыквенный пирог",
    img: "chocolate_pie.webp",
    variability_name: ["Шоколадный пирог", "Chocolate pie"],
  },
  {
    main: "PUMPKIN_PIE",
    info_item: "тыквенный пирог",
    img: "raspberry_pie.webp",
    variability_name: ["Малиновый пирог", "Raspberry pie"],
  },
  {
    main: "PUMPKIN_PIE",
    info_item: "тыквенный пирог",
    img: "trifle.webp",
    variability_name: ["Трайфл", "Trifle"],
  },
  {
    main: "MUSHROOM_STEW",
    info_item: "тушённые грибы",
    img: "broth.webp",
    variability_name: ["Бульон", "Broth"],
  },
  {
    main: "MUSHROOM_STEW",
    info_item: "тушённые грибы",
    img: "pelmenei.webp",
    variability_name: ["Пельмени", "Pelmenei"],
  },
];
