export const animation_type = [
  "wooden_axe",
  "wooden_hoe",
  "wooden_pickaxe",
  "wooden_shovel",
  "wooden_sword",

  "iron_axe",
  "iron_hoe",
  "iron_pickaxe",
  "iron_shovel",
  "iron_sword",

  "stone_axe",
  "stone_hoe",
  "stone_pickaxe",
  "stone_shovel",
  "stone_sword",

  "gold_axe",
  "gold_hoe",
  "gold_pickaxe",
  "gold_shovel",
  "gold_sword",

  "diamond_axe",
  "diamond_hoe",
  "diamond_pickaxe",
  "diamond_shovel",
  "diamond_sword",

  "netherite_axe",
  "netherite_hoe",
  "netherite_pickaxe",
  "natherite_shovel",
  "netherite_sword",

  "netherite_helmet",
  "netherite_chestplate",
  "netherite_leggings",
  "netherite_boots",

  "gold_helmet",
  "gold_chestplate",
  "gold_leggings",
  "gold_boots",

  "iron_helmet",
  "iron_chestplate",
  "iron_leggings",
  "iron_boots",

  "diamond_helmet",
  "diamond_chestplate",
  "diamond_leggings",
  "diamond_boots",

  "elytra",
  "turtle_helmet",
  "shears",
  "shield",
  "trident",
  "bow",
  "crossbow",
  "flint_and_steel",
  "fishing_rod",
  "carrot_on_a_stick",
  "warped_fungus_on_a_stick",
]