export const ARRAY_MAPPINGS = {
  crossbow: "crossbow",
  bow: "bow",

  turtle_helmet: "turtle_helmet",
  netherite_helmet: "helmet",
  golden_helmet: "helmet",
  iron_helmet: "helmet",
  leather_helmet: "helmet",
  chainmail_helmet: "helmet",
  diamond_helmet: "helmet",

  netherite_boots: "netherite_boots",
  golden_boots: "boots",
  iron_boots: "boots",
  leather_boots: "boots",
  chainmail_boots: "boots",
  diamond_boots: "boots",

  netherite_chestplate: "chestplate",
  golden_chestplate: "chestplate",
  iron_chestplate: "chestplate",
  leather_chestplate: "chestplate",
  chainmail_chestplate: "chestplate",
  diamond_chestplate: "chestplate",

  netherite_leggings: "leggings",
  golden_leggings: "leggings",
  iron_leggings: "leggings",
  leather_leggings: "leggings",
  chainmail_leggings: "leggings",
  diamond_leggings: "leggings",

  stone_pickaxe: "pickaxe",
  wooden_pickaxe: "pickaxe",
  netherite_pickaxe: "pickaxe",
  diamond_pickaxe: "pickaxe",
  golden_pickaxe: "pickaxe",
  iron_pickaxe: "pickaxe",

  stone_axe: "axe",
  wooden_axe: "axe",
  netherite_axe: "axe",
  diamond_axe: "axe",
  golden_axe: "axe",
  iron_axe: "axe",

  stone_hoe: "hoe",
  wooden_hoe: "hoe",
  netherite_hoe: "hoe",
  diamond_hoe: "hoe",
  golden_hoe: "hoe",
  iron_hoe: "hoe",

  stone_shovel: "shovel",
  wooden_shovel: "shovel",
  netherite_shovel: "shovel",
  diamond_shovel: "shovel",
  golden_shovel: "shovel",
  iron_shovel: "shovel",

  stone_sword: "sword",
  wooden_sword: "sword",
  netherite_sword: "sword",
  diamond_sword: "sword",
  golden_sword: "sword",
  iron_sword: "sword",

  leather_horse_armor: "horse_armor",
  iron_horse_armor: "horse_armor",
  golden_horse_armor: "horse_armor",
  diamond_horse_armor: "horse_armor",

  trident: "trident",
  elytra: "elytra",
  shears: "shears",
  flint_and_steel: "flint_and_steel",
  fishing_rod: "fishing_rod",
  carrot_on_a_stick: "carrot_on_a_stick",
  warped_fungus_on_a_stick: "warped_fungus_on_a_stick",
};