import classNames from "classnames";
import React from "react";
import OneItem from "../../[0_grouped_0]-Shopkeepers/one-item/One-item";
import Pagination from "../../pagination/Pagination";
import CabSearch from "../cab-search/CabSearch";

import styles from "./LogTrade.module.scss";

const DATA_TEST = [
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Dalandis",
    count: "1",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "elytra",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [
        {
          id: "mending",
          lvl: 1,
        },
        {
          id: "unbreaking",
          lvl: 3,
        },
      ],
    },
  },
  {
    id: "1",
    shopper: "SoftPanda3",
    count: "4",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 32,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "sand",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
  {
    id: "1",
    shopper: "Niksa_Viento",
    count: "2",
    date: new Date().toUTCString(),
    price: {
      slot1: {
        id: "deepslate_diamond_ore",
        improvement: "",
        amount: 1,
        content: [],
        minecraft_custom: "",
        enchant: [],
      },
      slot2: {},
    },
    product: {
      id: "glass",
      improvement: "",
      amount: 1,
      content: [],
      minecraft_custom: "",
      enchant: [],
    },
  },
];

const LogTrade = () => {
  const logMap = () => {
    let arr = [];
    for (let i = 0; i < DATA_TEST.length; i++) {
      for (let n = 0; n < DATA_TEST[i].count; n++) {
        let single = (
          <div className={classNames(styles["one_trade"])}>
            <span className={classNames(styles["text"])}>{DATA_TEST[i].date}</span>
            <div className={classNames(styles["items"])}>
              <OneItem customLink=".." item={DATA_TEST[i].price.slot1} />
              <OneItem customLink=".." item={DATA_TEST[i].price.slot1} />
              <span className={classNames(styles["arrow_suggestions"])}>&#10132;</span>
              <OneItem customLink=".." item={DATA_TEST[i].product} />
            </div>
            <span className={classNames(styles["text"])}>{DATA_TEST[i].shopper}</span>
            {/*<span className={classNames(styles["text"], styles["w"])}>{DATA_TEST[i].count}х</span>*/}
          </div>
        );

        arr.push(single);
      }
    }

    return arr;
  };

  const data = logMap();

  return (
    <div className={classNames(styles["log_wrapper"])}>
      <CabSearch name="проданного товара" count={data.length} to="#" />
      <div className={classNames(styles["log_list"])}>
        <Pagination content={data} customLimit={8} />
      </div>
    </div>
  );
};

export default LogTrade;
